spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:studio?createDatabaseIfNotExist=true;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/studio?createDatabaseIfNotExist=True
    username: root
    password:
  jpa:
    show-sql: true
#    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
#      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
# spring.jpa.show-sql = true


# spring.jpa.hibernate.ddl-auto = create